#!/bin/bash

if [[ -z $1 ]]; then
    echo "Error : Vesper command need additional paramater"
fi


appdir=/install/scripts
reldir=$(pwd)


if [[ $1 == "--install" ]];then
    /bin/bash $appdir/library/installs &&
    exit
fi

if [[ $1 == "--build" ]];then
   /bin/bash $appdir/library/build &&
   exit
fi

if [[ $1 == "--deploy" ]];then
    /bin/bash $appdir/library/deploy &&
    exit
fi

if [[ $1 == "--reset" ]];then
    /bin/bash $appdir/library/reseter &&
    exit
fi

if [[ $1 == "--getapp" ]];then
    /bin/bash $(pwd)/scripts/library/getpkg $reldir &&
    exit
fi

if [[ $1 == "--update" ]];then
    echo "pull repository" && git pull && 
    echo "populating file" && git add . &&
    echo "commit  changes" && git commit -m "$(date)" &&
    echo "push to gitrepo" && git push &&
    exit
fi