#!/bin/bash

xrandr --output eDP-1 --scale 1x1.08

SCRIPT_DIR=/home/child/.local/games/nintendo-switch/engine

if [ -f "$SCRIPT_DIR/Ryujinx.Headless.SDL3" ]; then
    RYUJINX_BIN="Ryujinx.Headless.SDL3"
fi

if [ -f "$SCRIPT_DIR/Ryujinx" ]; then
    RYUJINX_BIN="Ryujinx"
fi

if [ -z "$RYUJINX_BIN" ]; then
    exit 1
fi

COMMAND="env LANG=C.UTF-8 DOTNET_EnableAlternateStackCheck=1"

if command -v gamemoderun > /dev/null 2>&1; then
    COMMAND="$COMMAND gamemoderun"
fi

exec $COMMAND "$SCRIPT_DIR/$RYUJINX_BIN" "$@"